export class ForecastUnits {
  airPressureAtSeaLevel: string = "";
  airTemperature: string = "";
  airTemperatureMax: string = "";
  airTemperatureMin: string = "";
  cloudAreaFraction: string = "";
  cloudAreaFractionHigh: string = "";
  cloudAreaFractionLow: string = "";
  cloudAreaFractionMedium: string = "";
  dewPointTemperature: string = "";
  fogAreaFraction: string = "";
  precipitationAmount: string = "";
  precipitationAmountMax: string = "";
  precipitationAmountMin: string = "";
  probabilityOfPrecipitation: string = "";
  probabilityOfThunder: string = "";
  relativeHumidity: string = "";
  uvIndexClearSkyMax: string = "";
  windFromDirection: string = "";
  windSpeed: string = "";
  windSpeedOfGusts: string = "";
}