name: Angular

on:
  push:
    branches-ignore: [ "main" ]
  pull_request:
    branches-ignore: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Node setup
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies and build
      run: |
        npm ci
        npm run build:ci

    # - name: Test
    #   run: npm test --no-watch --no-progress --browsers=ChromeHeadless

    - name: Get version
      run: |
        VERSION=$(jq -r '.version' package.json)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        if [[ "$VERSION" != *"-"* ]]; then
          echo "RELEASE_IMAGE=true" >> $GITHUB_ENV
        elif [[ "$VERSION" == *"rc"* ]]; then
          echo "RELEASE_IMAGE=true" >> $GITHUB_ENV
        else
          echo "RELEASE_IMAGE=false" >> $GITHUB_ENV
        fi
        echo "Resolved version: $VERSION"
        
    - name: Build Docker image
      run: |
        docker run --rm --privileged tonistiigi/binfmt --install all
        docker buildx build --platform linux/arm64 --load \
          -f ./easy-tour-choice-frontend.dockerfile \
          -t ${{ secrets.DOCKER_USERNAME }}/easy-tour-choice-frontend:${{ env.VERSION }} .