name: Angular

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Node setup
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies and build
      run: |
        npm ci
        npm run build:ci

    - name: Test
      run: npm test --no-watch --no-progress --browsers=ChromeHeadless

    - name: Get version
      run: |
        VERSION=$(jq -r '.version' package.json)
        echo "Version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker run --rm --privileged tonistiigi/binfmt --install all
        docker buildx build --platform linux/arm64 --load \
          -f ./easy-tour-choice-frontend.dockerfile \
          -t ${{ secrets.DOCKER_USERNAME }}/easy-tour-choice-backend:${{ env.VERSION }} .

    - name: Push Docker image
      if: github.event_name == 'push' && env.RELEASE_IMAGE == 'true'
      run: |
        docker push "${{ secrets.DOCKER_USERNAME }}/easy-tour-choice-frontend:${{ env.VERSION }}"

    - name: Create tag
      if: github.event_name == 'push' && env.RELEASE_IMAGE == 'true'
      id: create_tag
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag -a "v${{ env.VERSION }}" -m "Release version ${{ env.VERSION }}"
        git push origin "v${{ env.VERSION }}"